shallow_clone: true

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2017

cache:
  - C:\cmake-3.13.0-win32-x86

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.13.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.13/cmake-3.13.0-win32-x86.zip'
        7z x -y cmake-3.13.0-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.13.0-win32-x86\bin;$env:PATH"

before_build:
  - cmd: set CXXFLAGS="/WX"
  - ps: |
      mkdir build
      cd build

      $env:generator="Visual Studio 15 2017"

      if ($env:PLATFORM -eq "x64") {
          $env:generator="$env:generator Win64"
      }
      echo generator="$env:generator"
      cmake .. -G "Visual Studio 15 2017"

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure
